server {
    listen 8080;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;
    location / {
        add_header Content-Security-Policy "frame-ancestors 'self' http://localhost:3000 http://localhost:5174;" always;
        add_header X-Frame-Options "SAMEORIGIN" always;
        try_files $uri $uri/ /index.html;
    }
}
